version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ruby
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db
volumes:
  db:
